source "https://rubygems.org"

ruby "3.3.0"

gem "rails", "~> 7.1"
gem "sqlite3", "~> 1.7"
gem "puma", "~> 6.4"

group :development, :test do
  gem "rspec-rails", "~> 6.1"
  gem "rubocop", require: false
end

group :development do
  gem "web-console", ">= 4.2.0"
end
